### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by FlyingAppleFish** [JoanKing/JKSwiftExtension#12]
建议说一下怎么引入包进行使用，我这边直接引入 -  @_exported import JKSwiftExtension，没法使用，提示找不到文件

**Comment by JoanKing** [comment]
如果是Swift项目
第一种：在单个文件里面导入 import JKSwiftExtension
第二种：创建一个 项目名.Bridging-Header文件(桥接文件)，导入：#import <JKSwiftExtension/JKSwiftExtension-Swift.h>
有其他问题可以加我微信交流：wangc2318151015
