### ISSUE TITLE
UITextView再设置placeholder之后 再次设置.text会出现text和placeholder覆盖的情况

### ISSUE THREAD

**Issue by dedencLichKing** [JoanKing/JKSwiftExtension#17]
首先现象是如图
![image](https://user-images.githubusercontent.com/28124734/150455960-fe9d41d0-889d-4b95-8584-9afe88d7e15b.png)

在demo工程里面 UITextView使用placeholer，设置了占位文字，在没有编辑的情况下，再重新设置了text文字 会出现覆盖的样子。

![image](https://user-images.githubusercontent.com/28124734/150456346-f55905d8-05eb-46bc-b810-24a257cb0f3a.png)

虽然我看源码是说 需要提前设置text 不然会出现计算问题。 但是目前我们确实有这个场景。

场景是这样子的，有一个输入框输入原因这个输入框是tableviewcell的一个控件，如果没有数据，就展示placeholder占位文字，如果有后端返回的数据需要显示text。
所以会出现这种问题。

我看了下修改起来其实很简单，不知道作者大大下次更新的时候 会修复这个小问题吗 十分感谢

**Comment by JoanKing** [comment]
UITextView去除PlaceHolder相关代码，建议使用JKPlaceHolderTextView设置PlaceHolder
