### ISSUE TITLE
timer 

### ISSUE THREAD

**Issue by plkgq** [JoanKing/JKSwiftExtension#18]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/11607068/155098573-9a388076-890a-4ec4-90e6-73e0c20fbb0f.png">
创建一个定时的timer
timer = JKWeakTimer(timeInterval: 0.1, target: self, selector: #selector(), userInfo: nil, repeats: true)
deinit时会崩溃

**Comment by plkgq** [comment]
Thread 1: EXC_BREAKPOINT

**Comment by plkgq** [comment]
具体来说，当创建一个定时的timer = JKWeakTimer(timeInterval: 10, target: self, selector: #selector(), userInfo: nil, repeats: true)
如果此时time还没有启动执行fire函数，这时退出当前controller，执行deinit函数就会崩溃， 若执行过fire，不会崩溃

**Comment by JoanKing** [comment]
在JKWeakTimer销毁的方法里面修复了，具体的您看 invalidate() 方法，具体如下
dispatch_suspend 状态下直接释放定时器，会导致定时器崩溃。初始状态，挂起状态，都不能直接调用
 dispatch_source_cancel(timer);调用就会导致app闪退，先调用下 dispatch_resume后再cancel，然后再释放timer
