### ISSUE TITLE
append报错

### ISSUE THREAD

**Issue by tangbing** [JoanKing/JKSwiftExtension#19]
// MARK: 1.2、数组新增元素(可转入一个数组)
    /// 数组新增元素(可转入一个数组)
    /// - Parameter elements: 数组
    mutating func append(_ elements: [Element]) {
        for element in elements {
            self.append(element)
        }
    }

这个append，项目中用起来，跟系统的append冲突报错，建议Api 改为：appends

**Comment by JoanKing** [comment]
2.0.6版本已经修改
