### ISSUE TITLE
兼容xcode13.3版本

### ISSUE THREAD

**Issue by plkgq** [JoanKing/JKSwiftExtension#20]
<img width="1080" alt="截屏2022-03-15 上午11 56 26" src="https://user-images.githubusercontent.com/11607068/158303380-a93c1007-368c-4c87-bb2c-3003c6585100.png">

**Comment by plkgq** [comment]
打包时也会报错

**Comment by JoanKing** [comment]
2.0.8版本修复

**Comment by JoanKing** [comment]
2.0.8版本修复
