### ISSUE TITLE
2.0.8版本 Date分类下的方法 formatterTimeStringToDate 不可用

### ISSUE THREAD

**Issue by PetterLee** [JoanKing/JKSwiftExtension#21]
代码里创建了 public let jk_formatter = DateFormatter() 全局变量, 但是始终没有对  jk_formatter 的属性 dateFormat 赋值, 导致这个方法不能用
<img width="1011" alt="截屏2022-03-18 17 32 02" src="https://user-images.githubusercontent.com/22096428/158977577-bbcba803-a661-4e71-b5e9-63a67b27ff42.png">

**Comment by JoanKing** [comment]
2.0.9版本修复DateFormatter问题
