### ISSUE TITLE
JKWeakTimer 调用 pause 方法后没有将 timer 挂起, 释放时候或者再次 fire 的时候产生崩溃

### ISSUE THREAD

**Issue by PetterLee** [JoanKing/JKSwiftExtension#23]
<img width="1125" alt="截屏2022-04-22 20 16 56" src="https://user-images.githubusercontent.com/22096428/164713719-8b48c809-1f67-4315-9fc0-539f9ee802bb.png">

**Comment by JoanKing** [comment]
2.1.1版本修复了
