### ISSUE TITLE
打包时报错

### ISSUE THREAD

**Issue by bigpig911** [JoanKing/JKSwiftExtension#25]
let visualEffectView = UIVisualEffectView.jk.visualEffectView(size: visualEffectViewSize, alpha: alpha, style: style, isAddVibrancy: false) 这句代码打包时报错

**Comment by JoanKing** [comment]
稍等，我看下，目前您使用的是哪个版本？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoanKing/JKSwiftExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JoanKing/JKSwiftExtension] 打包时报错 (Issue #25)





 
let visualEffectView = UIVisualEffectView.jk.visualEffectView(size: visualEffectViewSize, alpha: alpha, style: style, isAddVibrancy: false) 这句代码打包时报错

**Comment by bigpig911** [comment]
最新版

**Comment by JoanKing** [comment]
嗯嗯，稍等，我看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoanKing/JKSwiftExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JoanKing/JKSwiftExtension] 打包时报错 (Issue #25)





 
最新版

**Comment by JoanKing** [comment]
我刚使用代码测试下了打包，没问题，方便的话我加您个微信？沟通下问题









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoanKing/JKSwiftExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JoanKing/JKSwiftExtension] 打包时报错 (Issue #25)





 
最新版

**Comment by bigpig911** [comment]
辛苦你了，是我的错，我重新编译了下，可以正常打包了哈，关了吧

**Comment by JoanKing** [comment]
好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoanKing/JKSwiftExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JoanKing/JKSwiftExtension] 打包时报错 (Issue #25)





 
辛苦你了，是我的错，我重新编译了下，可以正常打包了哈，关了吧

**Comment by JoanKing** [comment]
好的
