### ISSUE TITLE
UITextView的placeholder 属性设置无效

### ISSUE THREAD

**Issue by devintangbohu** [JoanKing/JKSwiftExtension#27]
UITextView的placeholder 属性设置无效

**Comment by JoanKing** [comment]
单独的 UITextView 扩展去除了placeholder设置，建议升级到最新版本，使用JKPlaceHolderTextView

**Comment by devintangbohu** [comment]
我是pod导入的，好像没有你说的那个组件，是需要将文件导入项目再桥接？

**Comment by JoanKing** [comment]
升级最新的版本
