### ISSUE TITLE
使用DateFormatter的地方建议增加locale参数

### ISSUE THREAD

**Issue by plkgq** [JoanKing/JKSwiftExtension#29]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/11607068/174019208-1e5a2cee-45e8-4b13-a2c9-63eaefe0ac84.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/11607068/174019544-8175558d-5ed2-4265-b6ed-2cdeda5876fc.png">

**Comment by JoanKing** [comment]
在新的版本：2.1.7专门加了本地化Local的支持
![截屏2022-06-17 18 24 47](https://user-images.githubusercontent.com/19670000/174280296-e0b18211-d5c0-4c0e-affb-238c023ef80a.png)
