### ISSUE TITLE
JKViewGradientDirection 写错了一个枚举

### ISSUE THREAD

**Issue by MrBugDou** [JoanKing/JKSwiftExtension#3]
![image](https://user-images.githubusercontent.com/12947653/118767843-ca4e3080-b86d-11eb-8cb3-8b303dd3ed0f.png)
应该是
case .vertical:
            return (CGPoint(x: 0, y: 0), CGPoint(x: 0, y: 1))

**Comment by JoanKing** [comment]
收到，我纠正下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月19日(星期三) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [JoanKing/JKSwiftExtension] JKViewGradientDirection 写错了一个枚举 (#3)





 

 应该是
 case .vertical:
 return (CGPoint(x: 0, y: 0), CGPoint(x: 0, y: 1))

**Comment by JoanKing** [comment]
1.6.0、修复枚举 JKViewGradientDirection 在 vertical 为 return (CGPoint(x: 0, y: 0), CGPoint(x: 0, y: 1))

**Comment by JoanKing** [comment]
修复枚举 JKViewGradientDirection 在 vertical 为 return (CGPoint(x: 0, y: 0), CGPoint(x: 0, y: 1))
