### ISSUE TITLE
限制输入长度问题

### ISSUE THREAD

**Issue by olderMonster** [JoanKing/JKSwiftExtension#35]
1、表情的长度计算不准确，此时应该是string.utf16.count相对来说比较准确
2、如果一直输入表情，那么此时的长度限制貌似无效

**Comment by JoanKing** [comment]
1、目前处理的是按照：string.count来处理的，这两天会更新一个版本
2、如果一直输入表情，如果设置的是长度10，最多输入10个表情

**Comment by olderMonster** [comment]
第二个问题是我弄错了，不好意思。
还有一个就是通过inputRestrictions限制长度时使用粘贴好像无效。

**Comment by JoanKing** [comment]
通过inputRestrictions限制长度时使用粘贴好像无效这个问题已经修复了，今天我更新版本

**Comment by JoanKing** [comment]
方便加个微信吗？微信说：wangc2318151015

**Comment by JoanKing** [comment]
2.3.4版本：UITextField+Extension.swift和UITextView+Extension.swift的输入限制方法inputRestrictions新增lenghType: StringTypeLength = .count参数
