### ISSUE TITLE
限制输入长度的时候输入字符加表情会偶现闪退

### ISSUE THREAD

**Issue by xiamoweinuan** [JoanKing/JKSwiftExtension#36]
<img width="1335" alt="截屏2022-11-15 10 10 14" src="https://user-images.githubusercontent.com/7007749/201809506-a23e826d-79c6-4a94-87db-3cfa8da5d8c9.png">

**Comment by JoanKing** [comment]
感谢反馈，我今天修复一下

**Comment by xiamoweinuan** [comment]
<img width="1302" alt="截屏2022-11-15 10 17 42" src="https://user-images.githubusercontent.com/7007749/201810342-bec72e76-5412-4616-bacc-c3efc48030fe.png">
谢谢，输入到最后输入不了的时候，再随便点击键盘或者切换表情就会出现

**Comment by JoanKing** [comment]
更新到tag：2.2.2 试试

**Comment by JoanKing** [comment]
崩溃使用的tag是多少？

**Comment by xiamoweinuan** [comment]
2.2.1.更新到2.2.2后，同样存在这个bug，更新的内容中UITextField+Extension中也没有

**Comment by xiamoweinuan** [comment]
<img width="1335" alt="截屏2022-11-15 11 18 39" src="https://user-images.githubusercontent.com/7007749/201818345-a95dbe62-9679-4df9-bc82-7f286080bea8.png">
必现步骤，限制5个长度后，输入四个表情，text = '😁😁😁😁'，切换到九宫格随便输入个 字母text = '😁😁😁😁a'后点击上方的联想词后崩溃

**Comment by JoanKing** [comment]
感谢细心反馈

**Comment by JoanKing** [comment]
2.2.3版本做了修复，您更新下试试

**Comment by xiamoweinuan** [comment]
多谢更新，已经没有崩溃了，但是限制长度的时候，UITextField(UITextView) 在做输入字符串长度限制时
有两种长度需求限制：

String.count ：中文、英文、表情emoji都长度都算一个
(String as NSString).length: 中文、英文长度算1，表情emoji长度为2、4、7等等

我们后端计算方式都是普通表情按照2来算的，这样就很难受，输入的时候还是得手动监听换算成String来计算长度，老哥，有时间能区分一下这个吗
