### ISSUE TITLE
UILabel 的扩展方法 (linesCountAndLinesContent), 计算当前行数和每行内容的方法中, 如果UILabel中包含表情会闪退

### ISSUE THREAD

**Issue by PetterLee** [JoanKing/JKSwiftExtension#39]
<img width="994" alt="iShot_2023-05-25_17 57 55" src="https://github.com/JoanKing/JKSwiftExtension/assets/22096428/4f502b52-60b0-4845-a61e-623ae18b3b3d">

崩溃在字符串截取的方法中, 需要对 UILab 中的字符串处理一下表情

**Comment by PetterLee** [comment]
eg: 舒服得很，可惜乡里没房子🏠

**Comment by JoanKing** [comment]
收到，今晚修复下

**Comment by JoanKing** [comment]
2.3.0修复字符串截取有表情崩溃的问题
