### ISSUE TITLE
自定义Cell子视图部分圆角显示异常

### ISSUE THREAD

**Issue by xyhuangjia** [JoanKing/JKSwiftExtension#4]
用snapkit 自定义Cell 子视图上做部分圆角页面，页面布局布局异常

**Comment by JoanKing** [comment]
cell布局使用SnapKit的时候，控件切部分圆角的时候，在布局后，先调用 layoutIfNeeded() 后再切圆角，如下
self.layoutIfNeeded()
testLabel.jk.addCorner(conrners: .bottomLeft, radius: 8)
