### ISSUE TITLE
UITextView 限制字数拼音问题

### ISSUE THREAD

**Issue by LiuSky** [JoanKing/JKSwiftExtension#41]
UITextView 限制字数拼音问题，如果我最后还有一个字，但是这个字的拼音是huang。你就输不出来。可以参考下
<img width="1125" alt="截屏2023-10-08 17 00 02" src="https://github.com/JoanKing/JKSwiftExtension/assets/3087745/56b14ec0-e78d-41cd-906c-fd3bd8884d90">
谢谢

**Comment by JoanKing** [comment]
感谢反馈，稍后我看下

**Comment by JoanKing** [comment]
参考了微信，微信等均不可输入，为了更多人个性化使用，UITextFiled和UITextView在高亮状态下可以设置属性isMarkedTextRangeCanInput输入(非高亮字数在限制范围内)，默认是不可输入

**Comment by LiuSky** [comment]
支持了？我看下

**Comment by JoanKing** [comment]
传属性isMarkedTextRangeCanInput = true

**Comment by LiuSky** [comment]
![IMG_4697](https://github.com/JoanKing/JKSwiftExtension/assets/3087745/93727bf4-06f0-4b4b-bb91-c3d6c6c25c9f)
还是不行

**Comment by LiuSky** [comment]
![IMG_4698](https://github.com/JoanKing/JKSwiftExtension/assets/3087745/121d7b1d-b9a1-4829-b250-f1eb788441f0)
![IMG_4699](https://github.com/JoanKing/JKSwiftExtension/assets/3087745/58f2e3e4-fa9b-4431-84ac-42f5bf947db8)
这个是我限制50个字，但是最后一个字我还是可以输入拼音很长。但是最后点击确认会截断。微信他们不太可能不能输入吧。觉得这个场景很常见才对

**Comment by JoanKing** [comment]
截断是肯定的，截断的是最后输入高亮的部分，微信和支付宝你都可以看下他们的签名

**Comment by JoanKing** [comment]
方便的话微信说吧：wangc2318151016
