### ISSUE TITLE
横屏下有些问题

### ISSUE THREAD

**Issue by iwangjiajun** [JoanKing/JKSwiftExtension#45]
这里的常量在横屏下都不能用，后续可否优化下😄
![WX20240108-112320@2x](https://github.com/JoanKing/JKSwiftExtension/assets/3774362/ba700652-9e32-4049-b216-88aff1725b2f)

**Comment by JoanKing** [comment]
2.5.8版本：isIphoneX这个判断是有问题的，改为了jk_isIPhoneNotch

// MARK: 1.13、是否是缺口屏幕(刘海屏)或者灵动岛的屏幕
// 是否是缺口屏幕(刘海屏)或者灵动岛的屏幕
public var jk_isIPhoneNotch: Bool {
    if #available(iOS 11.0, *) {
        if let window = UIApplication.jk.keyWindow {
            return window.safeAreaInsets.top > 0
        } else {
            return false
        }
    } else {
        return UIApplication.shared.statusBarFrame.height > 20
    }
}
