### ISSUE TITLE
addActionHandler的点击事件无效

### ISSUE THREAD

**Issue by bestyyo** [JoanKing/JKSwiftExtension#48]
objc_setAssociatedObject(self, &AssociateKeys.closure, action, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
需要改成
objc_setAssociatedObject(self.base, &AssociateKeys.closure, action, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)

**Comment by szmichaelyb** [comment]
OC 中怎么访问这些扩展？

**Comment by JoanKing** [comment]
OC 很多暂时没有适配

**Comment by JoanKing** [comment]
2.6.5版本做了修复
