### ISSUE TITLE
作者你好，有添加隐私清单的计划吗

### ISSUE THREAD

**Issue by losedMemory** [JoanKing/JKSwiftExtension#50]
JKSwiftExtension 有使用到systemUptime
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by JoanKing** [comment]
有，可以在自己项目加一个PrivacyInfo
![截屏2024-05-07 17 31 45](https://github.com/JoanKing/JKSwiftExtension/assets/19670000/89a13f80-4d56-4f71-b0eb-fbe12834037b)

**Comment by losedMemory** [comment]
我以为每个第三方都要加呢，多谢！！
