### ISSUE TITLE
Inquiry Regarding ITMS-90683 Issue with JKSwiftExtension

### ISSUE THREAD

**Issue by GlassOfRedWinemm** [JoanKing/JKSwiftExtension#53]
Dear JKSwiftExtension Team,

I hope this message finds you well.

I recently encountered an issue while uploading my app to App Store Connect. Despite not explicitly using the Photo Library in my app, I received the following message:

```
ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “xxx.app” bundle should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
```

Our app does not directly interact with the Photo Library. However, we have integrated `JKSwiftExtension` into our project. Could you please confirm if there are any references to the Photo Library within the `JKSwiftExtension` library that might be triggering this requirement? If so, could you provide guidance on how to properly handle this situation to comply with Apple's requirements?

Thank you for your support and assistance.

Best regards

**Comment by GlassOfRedWinemm** [comment]
JKSwiftExtension (2.6.6)

**Comment by JoanKing** [comment]
库中有用到苹果的API import Photos这个，就需要Info.plist添加 NSPhotoLibraryUsageDescription 描述，后我把import Photos使用去掉，您可以先在Info.plist添加NSPhotoLibraryUsageDescription不影响审核

**Comment by GlassOfRedWinemm** [comment]
> 库中有用到苹果的API import Photos这个，就需要Info.plist添加 NSPhotoLibraryUsageDescription 描述，后我把import Photos使用去掉，您可以先在Info.plist添加NSPhotoLibraryUsageDescription不影响审核

这并不理想，因为我们的应用并不使用照片库。

这种未使用的照片库引用可能会带来合规和安全风险，因为它会触发不必要的权限请求，可能会让用户感到困惑，并使我们的应用隐私政策变得复杂。

请问您能否检查并修复这个问题，或提供解决此问题的指导？感谢您对确保库中不包含未使用的敏感API引用的支持与理解。

**Comment by JoanKing** [comment]
更新2.6.7版本，Photos 移到库外
