### ISSUE TITLE
UITextView限制输入长度时,当达到最大长度后,选中部分或全部内容修改,没法修改

### ISSUE THREAD

**Issue by fengyunjue** [JoanKing/JKSwiftExtension#54]
UITextView限制输入长度时,当达到最大长度后,选中部分或全部内容修改,没法修改.理论上,可以修改才对吧.我尝试在代码里添加了这个内容,不知道是否可行.

![QQ_1723447599805](https://github.com/user-attachments/assets/a4415ec2-c072-4f87-a06d-81ceb6d52d0a)

**Comment by JoanKing** [comment]
方便的话加个微信交流下，看下您说的需求 wangc2318151015

**Comment by JoanKing** [comment]
2.6.8 进行了修复
