### ISSUE TITLE
baseBasicAnimation的repeatCount未设置

### ISSUE THREAD

**Issue by plkgq** [JoanKing/JKSwiftExtension#7]
![image](https://user-images.githubusercontent.com/11607068/134476636-c6c66f30-5764-4cec-92e6-d7fa7ac294e8.png)
外界chuan传入的repeatCount未设置

**Comment by JoanKing** [comment]
1.8.7版本修复了

**Comment by JoanKing** [comment]
1.7.8版本：CALayer+Extension中baseBasicAnimation动画repeatNumber: 重复的次数的使用
